### PR TITLE
Update Sega Saturn to Mednafen Saturn

### PR DESCRIPTION
**Pull request by RobLoach**
Hold off on merging this, as it's still building the image locally. Will report back when it completes or errors out.

This fixes https://github.com/escalade/LibreELEC.tv/issues/3 .

### CODE REVIEW

**Comment by RobLoach** [comment]
Failed on something unrelated to the new core:

```
/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -O2  -mmmx -msse -msse2 -mfpmath=sse -I../include -I/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include -D_GNU_SOURCE   -c -o label_file.o label_file.c
/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -O2  -mmmx -msse -msse2 -mfpmath=sse -I../include -I/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include -D_GNU_SOURCE   -c -o get_default_type.o get_default_type.c
/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -O2  -mmmx -msse -msse2 -mfpmath=sse -I../include -I/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include -D_GNU_SOURCE   -c -o avc.o avc.c
label_file.c:18:18: fatal error: pcre.h: No such file or directory
compilation terminated.
Makefile:131: recipe for target 'label_file.o' failed
make[3]: *** [label_file.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/libselinux-2.5/libselinux/src'
Makefile:28: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/libselinux-2.5/libselinux'
Makefile:11: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/rob/Documents/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/libselinux-2.5'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 1
```

**Comment by escalade** [comment]
I've added a fix for that just now, can you try again? I had another report about that in the forum as well.

**Comment by escalade** [comment]
1. The post_unpack fails because the the extracted dir is correct already
2. The Makefile is already in the main directory, so no make_target step is needed

Again, please do test your package before submitting a PR :)

PS: You know you can do "scripts/build package" to build only that specific package, right?

**Comment by RobLoach** [comment]
> Again, please do test your package before submitting a PR :)

Mentioned that in my original comment, asked to hold off on merging, since it's still building. My computer is pretty slow to build this, and still testing the latest change. On libusb haiku currently.

> The Makefile is already in the main directory, so no make_target step is needed

Whoa! That's so much faster!!! Thanks a lot :+1:

Just pushed another update, which should clean some of this up. Built locally here, would enjoy some QA to make sure it's up and running.

**Comment by escalade** [comment]
Squash the commits as well.

**Comment by RobLoach** [comment]
Squashinated.

**Comment by escalade** [comment]
Looks like you've got my libselinux commit in there as well, you'll need to amend that :)

**Comment by RobLoach** [comment]
Bah, just going to create a new PR. https://github.com/escalade/LibreELEC.tv/pull/5

**Comment by escalade** [comment]
You could have just reversed that change and squashed it again. FYI :)

**Pull request closed without merging**
