### PR TITLE
Add NXEngine (Cave Story)

### PR DESCRIPTION
**Pull request by RobLoach**
This adds Cave Story support directly to RetroArch.

### CODE REVIEW

**Comment by escalade** [comment]
Please squash the commits :)

**Comment by RobLoach** [comment]
@escalade Squashed! Thanks.

**Comment by escalade** [comment]
Thanks for the helping hand :)

**Comment by escalade** [comment]
Also, please test properly before submitting the PR next time, it wouldn't compile for either generic or rpi here because it used the wrong compiler. The unpack step was incorrect as well.

**Comment by RobLoach** [comment]
@escalade Ah, thanks! Didn't know `make_target()` was a thing. This will be very handy when pushing more cores forward.

**Pull request merged**
